all: orchestrateur noeudAdd1 noeudAdd2 noeudSub noeudMul noeudDiv


orchestrateur:
	g++ -Wall -Wextra -Werror -o orchestrateur orchestrateur.cpp

noeudAdd1:
	g++ -Wall -Wextra -Werror -o noeudAdd1 noeudAdd1.cpp

noeudAdd2:
	g++ -Wall -Wextra -Werror -o noeudAdd2 noeudAdd2.cpp

noeudSub:
	g++ -Wall -Wextra -Werror -o noeudSub noeudSub.cpp

noeudMul:
	g++ -Wall -Wextra -Werror -o noeudMul noeudMul.cpp

noeudDiv:
	g++ -Wall -Wextra -Werror -o noeudDiv noeudDiv.cpp


clean:
	rm orchestrateur noeudAdd1 noeudAdd2 noeudSub noeudMul noeudDiv